### ISSUE TITLE
Unread Notification Badge [Linux]

### ISSUE THREAD

**Issue by 0-Kirby-0** [Vencord/Vesktop#298]
Cross-platform duplicate of [this Win10 feature request](https://github.com/Vencord/Vesktop/issues/20).

Feature looks like this:
![notif_badge](<https://github.com/Vencord/Vesktop/assets/34664194/d8a52bbb-d234-4941-b4f2-6c434a93fa90>).

Note: Vanilla discord has a missing dependency in libunity which is responsible for notification badges, as referenced [in this thread](<https://github.com/flathub/com.discordapp.Discord/issues/228>).
As shown above, the feature works on vanilla discord after installing libunity (or on distros that come with it), but not on Vencord.

**Comment by HMassey** [comment]
I can corroborate this, though I've arrived at the same result through the same steps:
![image](https://github.com/Vencord/Vesktop/assets/52863961/98aa2b1b-b7f2-4fa9-a6be-b0b69f82b5b4)

I have a feeling it's just not being added to KDE's notification manager part when you install it, but I tried jamming it into plasmanotifyrc and still no dice.
I don't know if the notifications/badges is a more generic abstracted function though.

**Comment by justin13888** [comment]
I also don't see the badge while on GNOME. Unsure whether it's settings although I've looked everything possible. I know it works perfectly fine on Windows.

**Comment by JakobDev** [comment]
> I also don't see the badge while on GNOME.

Gnome does not support this Feature

**Comment by azzamsa** [comment]
The official Discord client has a red dot to show unread notifications.


![image](https://github.com/Vencord/Vesktop/assets/17734314/26f53eb7-2232-4287-b02a-dbb45da13c66)

**Comment by 0-Kirby-0** [comment]
My original issue seems to have been resolved. I don't know which version, unfortunately, but it works now. 
Thank you!

![2024-02-05_18-31](https://github.com/Vencord/Vesktop/assets/34664194/62128076-0c78-4dea-a983-985e40974ce1)

Leaving the issue open for related problems above, but I'm satisfied here. Have a good one!

**Comment by RileyInkTheCat** [comment]
I have this exact problem, running Vesktop on ArchLinux through the flatpak version, any ideas on how to fix?

**Comment by 0-Kirby-0** [comment]
> I have this exact problem, running Vesktop on ArchLinux through the flatpak version, any ideas on how to fix?

Double-check if you have libunity installed, since it's not a listed dependency. Beyond that I wouldn't know, but I wanted to point it out just in case.

**Comment by soko7awen** [comment]
(Fedora 39 KDE)
I had this problem while using the flatpak, installing the rpm resolved that exact issue. I am now able to see an unread notifications counter on the app icon in the taskbar. Unfortunately however, the system tray icon does not have this feature for me, is it supposed to? I normally have Discord minimized to the tray, so the taskbar app icon badge is not very useful for me. :alien:

**Comment by Elloer** [comment]
> > on endeavouros/arch, even after installing libunity i still do not get any notifications
> 
> How did you install it? What Desktop do you use?

I am also on EndeavourOS, KDE 6 desktop. I also have this problem even though I have libunity installed. Badges don't show up to display the number of discord notifications.

**Comment by Elloer** [comment]
> How did you install Vesktop?

via bauh I installed the flatpak.

**Comment by DexyStorm** [comment]
stock discord works fine for me on plasma6

**Comment by DexyStorm** [comment]
How I am testing:
1) Join a popular server.
2) Check if notification badge is there.
Observation: its there for Discord, but not Vesktop.

![image](https://github.com/Vencord/Vesktop/assets/49816258/456e5ef5-5224-49d9-925a-5eb1fc3ecfc5)


I have the same settings for Vesktop and for stock Discord and I get the badge for Discord, but not Vesktop. If you want, I can record a short YT video where I show it happening and stuff.

**Comment by DexyStorm** [comment]
Oh, sorry. There was a comment about it aswell so I thought we were talking about both. Kind of like the problem is caused by the same thing. Sorry!

**Comment by Vendicated** [comment]
> Enabling settings>Notifications>Enable Unread Message Badge adds a useless dot to the window title when there is no unread notification. (Option should be hidden and off as Vesktop has its own setting which actually toggles the badge under settings>Vesktop>Notification Badge)

this setting is not about enabling the badge itself, it's about enabling an undead message indicator

ping => number badge
unread messages (non pings, just any message in an unmuted channel) => dot

vesktop uses this setting
https://github.com/Vencord/Vesktop/blob/2733727a40a4cf542277dedcf89e87e7740f962d/src/renderer/appBadge.ts#L19-L27 (note how it sends -1 for unreads), but only supports the unread badge on windows and mac because Linux only supports numbers https://github.com/Vencord/Vesktop/blob/2733727a40a4cf542277dedcf89e87e7740f962d/src/main/appBadge.ts#L26-L29

**Comment by AstralPhnx** [comment]
> I think it's a good idea to give a explanation what is needed to make this work:
> 
>     1. Electron [currently checks the Desktop](https://github.com/electron/electron/blob/5ad8b4b7d16ff8026243251bac98bbcf343c77e3/shell/browser/linux/unity_service.cc#L63) before using the API. I had [removed this check](https://github.com/electron/electron/pull/41211), so this should be gone with the next Electron version, but for now you may have to set some environment variables, if your desktop is not in the list.
> 
>     2. Libunity must be installed and can be loaded by Electron. Sadly there's no message if libunity is not found, but as long as you have installed it, this should not be a problem.
> 
> 
> After that, the API should be working. But there's a problem in the API itself: You can't said that a counter should be displayed on Window foo. You can only give the API the filename of a desktop file and the counter will be displayed on all windows that belongs to this file. That means the following:
> 
>     1. Vesktop must be installed
> 
>     2. The name of the desktop file must be `vesktop.desktop`. Not any other name.
> 
>     3. The window must be connected to the desktop file.

Currently trying to figure this out on my end myself and it's (rightfully) being a real ballache with the flatpak and appimages which both use their own funny haha .desktop filenames and can't really be changed around all that easily without causing issues. 
Is this .desktop file thing an absolute requirement at this point? And heck, how would these types of notifications even work in a sandbox like a flatpak or appimage to begin with? How would it go about talking to libunity? Does that also need to be installed systemside as well as sandbox side?

**Comment by AstralPhnx** [comment]
> > being a real ballache with the flatpak and appimages which both use their own funny haha .desktop filenames
> 
> If you take a look at my PR, I use the `patch-desktop-filename` script, so Vesktop will use the correct `dev.vencord.Vesktop.desktop` filename. For AppImage there is no way to make this work.
> 
> > Is this .desktop file thing an absolute requirement at this point?
> 
> Yes. This is even a bigger problem on Wayland. On Wayland Apps can't set a Icon. The Icon from the desktop file is used instead. So if the Window is not connected to the correct desktop file, it will not have the correct Icon. If a Window is not connected to the correct desktop filename, it can cause other Issues too.
> 
> > And heck, how would these types of notifications even work in a sandbox like a flatpak or appimage to begin with?
> 
> It works with my Patch in the Flatpak. For AppImages (which are not sandboxed btw) there is no way to make this work out of the box.
> 
> > How would it go about talking to libunity? Does that also need to be installed systemside as well as sandbox side?
> 
> It only need to be installed in the Sandbox (which it already is).
> 
> Just a tip: If you use KDE you can run the command `gdbus call -e -d org.kde.KWin -o /KWin -m org.kde.KWin.showDebugConsole` to open the debug console and see which desktop filename is connected to a Window.

Can confirm having looked at your PR earlier and building Vesktop as a Flatpak with your changes added that tray notifications now function as expected under GNOME 46 using Dash To Dock and Dash To Panel. Hopefully that gets folded into the flatpak officially sooner rather than later.

**Comment by AstralPhnx** [comment]
> Adding `XDG_CURRENT_DESKTOP=KDE5` to `vesktop.desktop` along with installing libunity has this working on Plasma 6 for me! Some things to note though:
> 
>     1. Enabling `settings>Notifications>Enable Unread Message Badge` adds a useless dot to the window title when there is no unread notification. (Option should be hidden and off as Vesktop has its own setting which actually toggles the badge under `settings>Vesktop>Notification Badge`)
>        ![image](https://private-user-images.githubusercontent.com/52550063/325844946-8db1c855-80c4-4405-b5d1-53ab27024e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTc1NjEsIm5iZiI6MTcxNjI1NzI2MSwicGF0aCI6Ii81MjU1MDA2My8zMjU4NDQ5NDYtOGRiMWM4NTUtODBjNC00NDA1LWI1ZDEtNTNhYjI3MDI0ZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAyMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODMyZjFmZjA2MmZiNmJmY2EyNzJjMTIwYTI1MzE5MTI4MzgwOGE2ZjYxNzcyOWYwNGNkMDYxMzg0OWYyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yc69sNp1VRns7lLkVYn7Z2HHoPh_6Vq56zcrEF8IHnc)
> 
>     2. When there is an unread notification there is a redundant display count in the non-static window title. This is pointless with working badges. (hides the dot from 1. when active)
>        ![image](https://private-user-images.githubusercontent.com/52550063/325845223-59470107-0401-4800-9b11-691180cbd508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTc1NjEsIm5iZiI6MTcxNjI1NzI2MSwicGF0aCI6Ii81MjU1MDA2My8zMjU4NDUyMjMtNTk0NzAxMDctMDQwMS00ODAwLTliMTEtNjkxMTgwY2JkNTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAyMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MTg3OGNjMGQ2ODhmMGQzZGQ5NDE2ZjI1NjFlMzkyYmMxY2RmZDcxMTM5MjczMmM1MDkxNmU3MjQ3ZDliODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lpps3h45xzWUflvBqY96-QhtdxnW4utXCJHFAp8IfYk)

I should note that while this works for me for getting the panel notifications back over on GNOME, it seems to have the unintended side effect of entirely breaking vesktop's ability to open web links in my browser. I can click them all I want but firefox just doesn't open. No clue why.

**Comment by Andrew15-5** [comment]
Is the problem with tray icon not showing the unread messages can be discussed here or a separate issue must be created?

It doesn't work on Pop!_OS 22.04 GNOME 42.* Vesktop v1.5.2 Debian/Flatpak. I tried installing https://extensions.gnome.org/extension/615/appindicator-support/, but it doesn't seem to change anything. Is the session logout necessary or something else?

![image](https://github.com/Vencord/Vesktop/assets/37143421/4322ff53-9488-4ce9-bb1f-da4190c85b96)

**Comment by PavelDobCZ23** [comment]
> Seems this is broken again even with libunity and `XDG_CURRENT_DESKTOP=KDE5` being set. 

I can confirm, both native Discord and rpm Vencord don't show the badge on KDE, with libunity on the system.

**Comment by PavelDobCZ23** [comment]
> Plasma bug report time 💥
> 
> Edit: https://bugs.kde.org/show_bug.cgi?id=486245

Tbf I'm not sure that the issue is on the Plasma side of things, because apps not made in Electron, like Telegram, display the badge fine. Maybe Electron needs to update the way they handle this.

**Comment by Vendicated** [comment]
![image-220](https://github.com/Vencord/Vesktop/assets/45497981/80304c85-a4a2-480f-bda7-c68c9107f514)

is this not the fix? try building with that electron version and see if it works

**Comment by flying-sheep** [comment]
`gdbus` isn’t necessarily installed everywhere. Since this is an electron app, using a DBus library for node.js would probably be the way to go.

**Comment by JoveyMcJupi** [comment]
I can confirm that notification badges are still very much broken, both on KDE Plasma 6 and GNOME 46.

But, they work perfectly fine on KDE Plasma 5 and the Ubuntu Dock on Ubuntu. Not the default GNOME dash/dock, just the Ubuntu Dock.

**Comment by yllekz** [comment]
Can also confirm that the tray icon does not display unreads on Linux Mint Cinnamon (flatpak)

**Comment by yllekz** [comment]
> The issue should be fixed in Vesktop version 1.5.4 with `libunity` package installed.

I am not seeing the fix from Linux Mint.

**Comment by Andrew15-5** [comment]
I installed Discord and Vesktop 1.5.4 through Nix and only the first one shows notification badge on the tray icon.

**Comment by ArthxrXc** [comment]
am i the only one has this issue on fedora kde plasma 6 as of  february 2025?

**Comment by mrbigmouth502** [comment]
I'm using EndeavourOS KDE with the Flatpak. My Vesktop system tray icon doesn't have a notification dot, and this is a feature I rely on heavily. Are there any plans to add this?

**Comment by nfp0** [comment]
The notification counter was working until recently on Arch with libunity installed (from the AUR). But on some recent update (not sure what) it stopped working.

**Comment by Godly-Avenger** [comment]
@nfp0 Same issue happening with me!

**Comment by arc-nix** [comment]
Same issue in wayland compositors.
Tested with Arch & NixOS.
We should have at least an option to bring official discord tray icon.
For now, patching Discord with Vencord is the best option if you have this issue.

**Comment by MaheeGamage** [comment]
I have RHEL 9 and it seems really hard to install libunity in this machine. Does someone successfully installed the libunity in their RHEL computer?

**Comment by kurzon90** [comment]
Has there been any update to this? Not working for me on Fedora 43 / Plasma 6.

**Comment by flying-sheep** [comment]
#1180 introduced native dbus badge count updating, which doesn’t rely on libunity being present on your system anymore.

That PR was released as part of Vesktop [1.6.0](https://github.com/Vencord/Vesktop/releases/tag/v1.6.0), so if you have at least that version, it should work reliably.

Maybe Flatpak shenanigans prevent that, but the rpm version should definitely work for you.

**Comment by arc-d3v** [comment]
I can confirm that it works on wayland compositors, tested on Hyprland, Niri and Sway with waybar.

**Comment by Andrew15-5** [comment]
I noticed that that PR supposedly closes 3 issues, yet they are listed on one line, making only the first one to auto-close upon merging, leaving 2 others, including this one, still open. Though technically this is about KDE, but now the badge is also fixed on GNOME, so probably on KDE as well.

Cc @Vendicated

**Comment by yllekz** [comment]
For me on Linux Mint, the icon has been changed out and the new one now works. The notification indicator is subtle but it DOES work (it's a small dot earby the "VC" icon). This should be totally fixed now.

**Comment by Andrew15-5** [comment]
Supposedly, the dot will be bigger at some point. https://github.com/Vencord/Vesktop/pull/1180#issuecomment-3369308127

**Comment by IdrisQe** [comment]
So, this is supposed to be fixed if one has Vesktop 1.6.0 or above?
Does it require a reinstall? Or any other process?

Because I'm on Bazzite (Fedora 43 based), using KDE Plasma 6, and Vesktop 1.6.1 Flatpak, and my taskbar icon still does not get any badges. No dot, no number. The tray icon does get badges correctly still but that has always worked for me.

Maybe it's the .desktop file? What should the .desktop file contain, be named, and where should it be located for the flatpak version? Because I did have to fiddle with the .desktop file in the past to fix an issue, so I wonder if it's broken because of that still, even though updates should have overwritten my changes?

Or maybe do I need to enable a specific Flatpak permission with Flatseal or something? D-Bus Session Bus or D-Bus System Bus perhaps given it's using D-Bus now? Those are still disabled like they were when I first installed Vesktop.

**Comment by TomasGo02** [comment]
Is this meant to address both the badge on the tray and the dock (mention count number) or just the tray? As I have the red dot on the tray but nothing on the dock.

**Comment by ubergeek77** [comment]
> [#1180](https://github.com/Vencord/Vesktop/pull/1180) introduced native dbus badge count updating, which doesn’t rely on libunity being present on your system anymore.
> 
> That PR was released as part of Vesktop [1.6.0](https://github.com/Vencord/Vesktop/releases/tag/v1.6.0), so if you have at least that version, it should work reliably.
> 
> Maybe Flatpak shenanigans prevent that, but the rpm version should definitely work for you.

Then I guess no unread counts is a Flatpak issue. I'm on Bazzite as well, so I use Flatpak apps. But the [official Discord flatpak](https://flathub.org/en/apps/com.discordapp.Discord) has unread counts that work perfectly fine. For as long as I've used Bazzite (October 2025), the official Discord Flatpak has always had unread counts on Bazzite, but Vesktop never has and still doesn't even after this change:
<img width="108" height="60" alt="Image" src="https://github.com/user-attachments/assets/7eba0add-6b2f-4475-ae83-119238472590" />

I don't know if the tray indicator was ever an issue, but that works fine on both as of today (Vesktop 1.6.5):
<img width="124" height="117" alt="Image" src="https://github.com/user-attachments/assets/49a53517-a23c-4cab-8d41-752a6b925f1c" />

Since the official Discord Flatpak does not have this issue, can we reopen this one, or make a new one to track the Flatpak specific issue?

**Comment by Leefy1** [comment]
> Then I guess no unread counts is a Flatpak issue. I'm on Bazzite as well, so I use Flatpak apps. But the [official Discord flatpak](https://flathub.org/en/apps/com.discordapp.Discord) has unread counts that work perfectly fine. For as long as I've used Bazzite (October 2025), the official Discord Flatpak has always had unread counts on Bazzite

Hey, I'm on Bazzite with the official Discord flatpak. Did they work without editing anything? The badges don't show up for me, on KDE.

**Comment by ubergeek77** [comment]
> > Then I guess no unread counts is a Flatpak issue. I'm on Bazzite as well, so I use Flatpak apps. But the [official Discord flatpak](https://flathub.org/en/apps/com.discordapp.Discord) has unread counts that work perfectly fine. For as long as I've used Bazzite (October 2025), the official Discord Flatpak has always had unread counts on Bazzite
> 
> Hey, I'm on Bazzite with the official Discord flatpak. Did they work without editing anything? The badges don't show up for me, on KDE.

I didn't do anything special. You may have it turned off in Discord settings. The unread badges on the Discord Flatpak have always worked on KDE Bazzite. Vesktop's badges never have and still don't.

On that note, can this issue be reopened please? It's not correct to blame this on Flatpak when the official Discord Flatpak is clearly working fine.

**Comment by IdrisQe** [comment]
> > > Then I guess no unread counts is a Flatpak issue. I'm on Bazzite as well, so I use Flatpak apps. But the [official Discord flatpak](https://flathub.org/en/apps/com.discordapp.Discord) has unread counts that work perfectly fine. For as long as I've used Bazzite (October 2025), the official Discord Flatpak has always had unread counts on Bazzite
> > 
> > 
> > Hey, I'm on Bazzite with the official Discord flatpak. Did they work without editing anything? The badges don't show up for me, on KDE.
> 
> I didn't do anything special. You may have it turned off in Discord settings. The unread badges on the Discord Flatpak have always worked on KDE Bazzite. Vesktop's badges never have and still don't.
> 
> On that note, can this issue be reopened please? It's not correct to blame this on Flatpak when the official Discord Flatpak is clearly working fine.

Ah, Vesktop's never have? Then why was this issue closed?

**Comment by Leefy1** [comment]
They suddenly work with normal discord now for me
Edit: after re-installing vencord onto normal discord they don't work anymore.

**Comment by ubergeek77** [comment]
I gave up on Vesktop ever having this properly fixed, this issue should have been reopened 5 months ago.

Since I've never had issues with the official Flatpak, I now make my own Flatpak from the [official manifest](https://github.com/flathub/com.discordapp.Discord), and I add a build step that runs the Vencord CLI before packaging. Badges work and everything. If the official Flatpak is broken for you then there must be something wrong with your KDE configuration somehow 🤔

**Comment by Leefy1** [comment]
I have the official Flatpak and the badges work without Vencord, and I'm not using Vesktop.
