### ISSUE TITLE
[Bug] Share screen with audio causes loud audio spikes for streamer

### ISSUE THREAD

**Issue by Different-Name** [Vencord/Vesktop#772]
### Discord Account

different_name

### Operating System

NixOS

### Linux Only ~ Desktop Environment

Hyprland

### Package Type

Flatpak & nixpkgs

### What happens when the bug or crash occurs?

When sharing screen with audio, me - the person screen sharing, will occasionally experience a very loud spike in volume for a split second. This only occurs when streaming with audio
I tried recording this through obs, but the audio spike does not occur in the recording

### What is the expected behaviour?

Consistent system volume whilst streaming with audio

### How do you recreate this bug or crash?

1. Start a stream with audio (entire system or application, doesn't matter)
2. Use computer normally, with sound playing

### Debug Logs

Logs from starting vesktop to when the issue occured
```console
$ flatpak run dev.vencord.Vesktop

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/different/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0720/210557.454761:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0720/210557.695957:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0720/210557.696011:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:3) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/different/.var/app/dev.vencord.Vesktop/config/vesktop/settings/quickCss.css'
    at async open (node:internal/fs/promises:636:25)
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
{ discordBranch: 'stable', minimizeToTray: 'on' }
[3:0720/210630.162870:ERROR:shared_x_display.cc(39)] Unable to open display
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-07-20 21:06:32.400] [venmic] [info] [patchbay] (handle) found default metadata: 41
[2024-07-20 21:06:32.401] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Speaker__sink"
[2024-07-20 21:06:32.401] [venmic] [info] [patchbay] (get) running venmic 6.1.0
[2024-07-20 21:06:37.029] [venmic] [info] [patchbay] (create_mic) created: 152
[3:0720/210637.058050:ERROR:shared_x_display.cc(39)] Unable to open display
[3:0720/210637.102114:ERROR:shared_x_display.cc(39)] Unable to open display
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Different-Name** [comment]
I use the nixpkgs day to day, did a fresh install of the flakpak today for this issue and same result. I did not import or configure any vesktop settings on the flatpak, I only signed in and started a stream. So I don't think this is configuration related

**Comment by kotudemo** [comment]
I have the same issue on Windows

**Comment by kekkodance** [comment]
same

**Comment by dotaxis** [comment]
I have been wondering for a long time what was causing these audio spikes and didn't realize it was only happening while I was streaming. I even bought a new DAC because I thought that was the culprit.

How bizarre.

Arch btw

**Comment by dweee** [comment]
Across Windows and NixOS too.

**Comment by megumann** [comment]
> Across Windows and NixOS too.

I can confirm that this is occurring on Windows systems as well. Those who watch the stream report being able to hear audio system-wide instead of isolated to the application when streaming a specific window.

**Comment by Different-Name** [comment]
Tried this on Windows today, more like the audio stutters than the spikes I got on NixOS. Very different sound

**Comment by a-usr** [comment]
Venmic version: 3.4.2
Vesktop version:
The nodes in qpwgraph (`PRO Mono` is the mic):
![image](https://github.com/user-attachments/assets/30599edf-f1a1-4294-8106-d490a05c8adf)
[venmic log](https://github.com/user-attachments/files/16996139/venmic.txt)

not sure what you mean with venmic settings or where I can find them

**Comment by Curve** [comment]
> Venmic version: 3.4.2
> Vesktop version: 
> ```
> stable 326854 (2e9e66d) Build Override: N/A
> Vencord f27361f (Vesktop v1.5.2)
> Electron 31.4.0
> Chromium 126.0.6478.234
> ```
> The nodes in qpwgraph (`PRO Mono` is the mic):
> ![image](https://github.com/user-attachments/assets/30599edf-f1a1-4294-8106-d490a05c8adf)
> [venmic log](https://github.com/user-attachments/files/16996139/venmic.txt)
> 
> not sure what you mean with venmic settings or where I can find them

The problematic node in this case is the Titanfall one?

The Venmic settings are the audio share settings shown when starting a screen share.

**Comment by a-usr** [comment]
> The problematic node in this case is the Titanfall one?

Yes, to be specific its the `Titanfall 2 [audio stream #1]` node. In the game it is used for voice chat.

> The Venmic settings are the audio share settings shown when starting a screen share.

Ah. Apart from setting the audio source to Titanfall 2 instead of the entire system I dont change anything. I'd also like to add that the issue only occurs if I do that, when venmic listens to the entire system it doesn't connect to that listen node.

Also sorry for taking so long 😬

**Comment by Curve** [comment]
> 
> > The problematic node in this case is the Titanfall one?
> 
> Yes, to be specific its the `Titanfall 2 [audio stream #1]` node. In the game it is used for voice chat.
> 
> > The Venmic settings are the audio share settings shown when starting a screen share.
> 
> Ah. Apart from setting the audio source to Titanfall 2 instead of the entire system I dont change anything. I'd also like to add that the issue only occurs if I do that, when venmic listens to the entire system it doesn't connect to that listen node.
> 
> Also sorry for taking so long 😬
> 
> 

Thanks for the info, seems like the Titanfall node does not have the proper media class, which is why that happens.

This should be an easy fix, I will probably issue an update by the end of the week.

Are you on the vencord discord by any chance? 
If so, would you be willing to test the fix before I issue a release? (Ping me in the vesktop-development channel, name is the same as on GitHub) That would help a lot ^^

**Comment by a-usr** [comment]
> Are you on the vencord discord by any chance? If so, would you be willing to test the fix before I issue a release? (Ping me in the vesktop-development channel, name is the same as on GitHub) That would help a lot ^^

Not right now, since I'm at work atm, but if I remember when I get home sure!

**Comment by PaulRicharte** [comment]
Can confirm the issue on Fedora 41 as well. I'm willing to test any patch if wanted!

**Comment by megumann** [comment]
> > Across Windows and NixOS too.
> 
> I can confirm that this is occurring on Windows systems as well. Those who watch the stream report being able to hear audio system-wide instead of isolated to the application when streaming a specific window.

Since this post I can confirm this issue is present on Arch Linux; both using X11 and Wayland on Pipewire. It occurs typically when starting a stream, and at random during it. I also note that sharing the entirety of the display will sometimes produce stuttering. 

In my experience on Arch, I have been using a GNOME desktop. This issue existed in GNOME 46 and persists into GNOME 47, which helps to solidify the likelihood that this is an audio/video processing issue and not a desktop issue. 

Issues occur on Windows specifically when using the Vesktop client. I don't think this is an issue with Linux A/V processing, and more with Vesktop's method.

**Comment by sayidabyan** [comment]
can confirm. I wonder if this is also  related with my issue where the shared audio is going too low and high as if it's getting noise cancelled.

**Comment by different-name** [comment]
> can confirm. I wonder if this is also related with my issue where the shared audio is going too low and high as if it's getting noise cancelled.

I stopped using Vesktop (and Vencord) all together after they removed the issues tab on this repo, glad it seems to be back now. The native Discord client works flawlessly on Wayland thanks to some work they did on it a couple months ago - I recommend trying that

**Comment by different-name** [comment]
Theres some good info on this issue scattered somewhere in the Vesktop support channel from when we were trying to debug this while the issues tab was removed here

**Comment by Vendicated** [comment]
> can confirm. I wonder if this is also related with my issue where the shared audio is going too low and high as if it's getting noise cancelled.

disable autogain in discord voice and video settings.

**Comment by different-name** [comment]
> disable autogain in discord voice and video settings.

Iirc, looking at qpwgraph while the issue was happening, this was because multiple source nodes would get piped into the sink on occasion, and they stacked on top of eachother

**Comment by Curve** [comment]
> > disable autogain in discord voice and video settings.
> 
> Iirc, looking at qpwgraph while the issue was happening, this was because multiple source nodes would get piped into the sink on occasion, and they stacked on top of eachother

A link creation should not cause audio spikes in and of itself

**Comment by kittibyte** [comment]
> > can confirm. I wonder if this is also related with my issue where the shared audio is going too low and high as if it's getting noise cancelled.
> 
> I stopped using Vesktop (and Vencord) all together after they removed the issues tab on this repo, glad it seems to be back now. The native Discord client works flawlessly on Wayland thanks to some work they did on it a couple months ago - I recommend trying that

why is this hidden as off topic lmao? this is genuinely good info to have, knowing its not a bug with the official client means 1. people can just use that temporarily until the bug is solved and 2. confirms this isnt a bug on discords end and could help with solving the issue

**Comment by DaddlJ** [comment]
I'm having the same problem accross multiple platforms and package-types.

Platforms:
- Fedora Linux 42 (Gnome 48) (rpm/Flatpak)
- CachyOS (KDE-Plasma 6.4.3) (Flatpak)

At the start of a stream with audio (doesn't matter if a window or a screen is shared) the audio spikes and gets a lot louder for a split second. It also happens randomly sometimes in the middle of a stream.

**Comment by jayebunny** [comment]
Nobara 42

Watching my audio via QJackCtl graphs, when the spike occurred there was a new Chromium output created for a few seconds then vanished. “Chromium-147”. Tied directly into my Streamer X Analog Stereo playback nodes. Doesn’t tie-in to the vencord-screen-share node at all.

**Comment by jadedcthulhu** [comment]
Having this issue on CachyOS (Arch Linux), any idea on what the cause may be from everything posted?

**Comment by BTekV4** [comment]
Same here Bazzite Gnome

**Comment by Luminance69** [comment]
Bazzite KDE same issue

**Comment by chrisheib** [comment]
NixOS KDE Wayland, have the loudness spikes, and also problems with audio for the listener: The volume of the streamed audio fluctuates heavily for my viewers. Regardless of their or mine audio settings in discord, the mic being muted or not, loud or quiet source...

**Comment by mr00k3** [comment]
Same thing on hyprland and pipewire

**Comment by Concibar** [comment]
> NixOS KDE Wayland, have the loudness spikes, and also problems with audio for the listener: The volume of the streamed audio fluctuates heavily for my viewers. Regardless of their or mine audio settings in discord, the mic being muted or not, loud or quiet source...

I'm also on NixOS and I have the loudness spikes when streaming.
My Partner is on Arch, same problem. Also when she streams the audiostream volume fluctuates quite a bit just as @chrisheib described.

**Comment by GamertechAU** [comment]
Getting this with the Vesktop flatpak capturing a specific window and limited to that window's audio. When it happens, the green active border appears around the stream window itself indicating that it's got a hot mic.

Only appears for a second but I hear both the normal audio being shared and Vesktop itself feeds the same audio back to me.

No interactions with the PC at all when it happens. No keys pressed, no programs interacting etc. No noticeable trigger.

**Comment by munakoisovelho** [comment]
I'm using CachyOS and I'm having the same issue. I've noticed this happens every time when the stream preview picture updates every 5 minutes.

**Comment by JateaRH** [comment]
I am also noticing the same behavior that munakoisovelho reported, where I was watching the stream preview to notice when it changed, and I heard the "audio spike" and noticed that the stream preview image updated afterwards.

(My system is EndeavourOS, KDE Plasma)

**Comment by Solenyy27** [comment]
I also have this issue, Arch Linux w/ KDE Plasma.

Doesn't matter how many times I reinstall or where I pull it from. Upon starting screenshare I can always hear an initial instance of the audio glitch, which then happens at random throughout the screenshare. On qpwgraph it looks like 2 or 3 chromium nodes suddenly pop up for a sec, manage to connect in such a way to cause the loud noise, and then pop out of existence. 

Definitely different from the usual sources of random audio artifacts in the form of pipewire related/adjacent popping/crackling, since I was able to fix all of those with updates to my pipewire and wireplumber configs.

**Comment by Caitex212** [comment]
> I also have this issue, Arch Linux w/ KDE Plasma.
> 
> Doesn't matter how many times I reinstall or where I pull it from. Upon starting screenshare I can always hear an initial instance of the audio glitch, which then happens at random throughout the screenshare. On qpwgraph it looks like 2 or 3 chromium nodes suddenly pop up for a sec, manage to connect in such a way to cause the loud noise, and then pop out of existence.
> 
> Definitely different from the usual sources of random audio artifacts in the form of pipewire related/adjacent popping/crackling, since I was able to fix all of those with updates to my pipewire and wireplumber configs.

What configs did you change?

**Comment by Solenyy27** [comment]
> What configs did you change?

if we're talking about just starting from having nothing, I imported the defaults from /usr/share/pipewire
into .config/pipewire and uncommented the lines for link.max-buffers, default.clock.allowed-rates, and default.clock.min-quantum. Then, I set an override config with pulse.min.quantum to 1024/48000 to prevent audio crackling and prevent it from being overwritten during updates.

I did the same for jack.conf and uncommented log.level, node.latency,rate,quantum and force-quantum. These changes stopped crackling from happening during medium/high CPU loads.

to stop crackling/popping whenever an audio source starts, I set a override config in wireplumber to find any alsa output node and update its properties to have no suspend time. I have no idea where I found this solution, my apologies.

Regardless, none of those stopped the screenshare issue. It seems to be an issue with vesktop in particular, as using the AUR package of discord and installing vencord works fine and does not have the issue. Perhaps there is some kind of recursion or looping that happens upon starting the stream that gets picked back up every now and then?

**Comment by rri889** [comment]
Same issue on Arch KDE wayland , fixed by disabling stream previews, can be found in _**settings > voice & video > streaming > Show Stream Previews**_.

**Comment by SuperPenny64** [comment]
> Same issue on Arch KDE wayland , fixed by disabling stream previews, can be found in _**settings > voice & video > streaming > Show Stream Previews**_.

CachyOS KDE Wayland here. I can confirm that disabling stream previews fixes the issue. It's completely possible that the audio spike is happening whenever the stream preview is updated, which would explain why it first happens shortly after starting the stream and then repeats every few minutes.

**Comment by rw-root** [comment]
I had this Problem for a long time until i disabled Hardware Acceleration in the settings. my stream previews are disabled by default.

With the update i applied today, it is back even without Hardware Acceleration enabled. Due to this i installed the Default Discord app and it works perfectly fine.


OS - Garuda Linux x86_64
Kernel - Linux 6.18.9-zen1-2-zen
DE - KDE Plasma 6.6.0
Window Manager - KWin (Wayland)

CPU - AMD Ryzen 5 5600X (12) @ 4.65 GHz
GPU -NVIDIA GeForce RTX 3060 Lite Hash Rate [Discrete]
OpenGL - 4.6.0 NVIDIA 590.48.01
Vulkan 1.4.325 - NVIDIA [590.48.01]

UPDATE:

I disabled the "WebScreenShareFixes" Plugin and my audio problems are fixed, even with HA enabled.
now i have graphic issues but ig thats a different issue in itself

**Comment by wafflewizard1** [comment]
Turning off the screen share preview fixes it for the streamer but viewers still get fluctuating audio volume, although I know this isnt what this bug report is about.

**Comment by Overcrimp** [comment]
> I had this Problem for a long time until i disabled Hardware Acceleration in the settings. my stream previews are disabled by default.
> 
> With the update i applied today, it is back even without Hardware Acceleration enabled. Due to this i installed the Default Discord app and it works perfectly fine.
> 
> OS - Garuda Linux x86_64 Kernel - Linux 6.18.9-zen1-2-zen DE - KDE Plasma 6.6.0 Window Manager - KWin (Wayland)
> 
> CPU - AMD Ryzen 5 5600X (12) @ 4.65 GHz GPU -NVIDIA GeForce RTX 3060 Lite Hash Rate [Discrete] OpenGL - 4.6.0 NVIDIA 590.48.01 Vulkan 1.4.325 - NVIDIA [590.48.01]
> 
> UPDATE:
> 
> I disabled the "WebScreenShareFixes" Plugin and my audio problems are fixed, even with HA enabled. now i have graphic issues but ig thats a different issue in itself

Thank you for this, I was having the same issue where it was mainly a problem for those viewing my stream with infrequent spikes for me. Trying this out with the "WebScreenShareFixes" disabled and it immediately improved the audio.

**Comment by Curve** [comment]
This will be fixed in an upcoming update - the problem was not venmic itself, but chromium, which for some reason connects the node it pulls audio from for the screenshare to the speakers for a split second (venmic is connected to this node, thus the spike occurs).

See #1291

**Comment by BarkBarklington** [comment]
I'm hoping to see

> This will be fixed in an upcoming update - the problem was not venmic itself, but chromium, which for some reason connects the node it pulls audio from for the screenshare to the speakers for a split second (venmic is connected to this node, thus the spike occurs).
> 
> See [#1291](https://github.com/Vencord/Vesktop/pull/1291)

I'm hoping to see this get resolved :3

**Comment by pallaswept** [comment]
A bit of a cross-post here but, I'm still seeing this issue, as well as https://github.com/Vencord/venmic/issues/36 , in the Vesktop 1.6.7 appimage.

**Comment by Curve** [comment]
> A bit of a cross-post here but, I'm still seeing this issue, as well as https://github.com/Vencord/venmic/issues/36 , in the Vesktop 1.6.7 appimage. 

The venmic update was not included in Vesktop 1.6.7

**Comment by pallaswept** [comment]
Oh my bad sorry, I've jumped the gun. Thanks for letting me know, I'll look forward to it
